server:
  port: 8082
mysql:
  host: 127.0.0.1
  port: 3306
  userName: root
  password: 123456
  dbName: shop-dev-go
  # số lượng kết nối không hoạt động (idle) mà pool có thể duy trì mà không đóng chúng
  maxIdleConnection: 10
  maxOpenConnect: 100
  #  thời gian tối đa mà một kết nối có thể tồn tại
  connectMaxLifeTime: 3600
logger:
  loggerLevel: debug
  fileName: "./storages/logs/dev.001.log"
  maxSize: 500
  maxBackups: 3
  maxAge: 28
  compress: true